# Generated by Django 3.0.3 on 2020-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_auto_20190302_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Porto',
        ),
    ]
